on:
  - push
jobs:
  check-flake:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v29
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix flake check
